FROM ubuntu:latest

RUN apt-get update
RUN apt-get install python3 python3-pip -y

RUN pip3 install flask
RUN pip3 install mysql-connector-python
RUN pip3 install flask-SQLAlchemy
RUN pip3 install Flask-Migrate
RUN pip3 install pymySQL
RUN pip3 install cryptography
RUN pip3 install Flask-WTF
RUN pip3 install email_validator

RUN mkdir /app
